version: '3.7'

services:
    db:
        image: "postgres:alpine"
        env_file:
            - web.env
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data/

    weatherapi:
        build:
            context: .
        env_file:
            - web.env
        ports:
            - "8000:8000"
        volumes:
            - ./weatherAPI:/weatherAPI
        command: sh -c "python manage.py runserver 0.0.0.0:8000"
        environment: 
            - DEBUG=1
            - ALLOWED_HOSTS=127.0.0.1,localhost
        depends_on:
            - db

volumes:
    postgres_data: